/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.rishi.unimanagement.visual;

import com.rishi.unimanagement.data.Database;
import com.rishi.unimanagement.data.TAData;
import com.rishi.unimanagement.visual.option.StudentSelectionOption;
import com.rishi.unimanagement.visual.option.ChangePassOption;
import java.awt.CardLayout;
import javax.swing.JPanel;

public class TAPanel extends javax.swing.JPanel {
    private final TAData ta;
    private CardLayout cardLayout;
    private JPanel cardPanel;
    /**
     * Creates new form TAPanel
     */
    public TAPanel(CardLayout cardLayout, JPanel cardPanel, String name) {
        ta = (TAData) Database.getUserData(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editGradesButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        changePasswordButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        editGradesButton.setText("Edit Grades");
        editGradesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editGradesButtonActionPerformed(evt);
            }
        });

        String name = ta.getName();
        jLabel1.setText("Logged in as: %d" + name);

        changePasswordButton.setText("change password");
        changePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordButtonActionPerformed(evt);
            }
        });

        int section = ta.getSection();
        jLabel2.setText(String.format("Section: %d", section));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(changePasswordButton)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(editGradesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130))))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(editGradesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(changePasswordButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editGradesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editGradesButtonActionPerformed
        StudentSelectionOption panel = new StudentSelectionOption(ta);

        cardPanel.add(panel, "gradesEdit");
        cardLayout.show(cardPanel, "gradesEdit");
    }//GEN-LAST:event_editGradesButtonActionPerformed

    private void changePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordButtonActionPerformed
        ChangePassOption panel = new ChangePassOption(ta);

        cardPanel.add(panel, "changePass");
        cardLayout.show(cardPanel, "changePass");
    }//GEN-LAST:event_changePasswordButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changePasswordButton;
    private javax.swing.JButton editGradesButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
